apiVersion: v1
kind: ConfigMap
metadata:
  name: http-proxy-env-config
data:
  NO_PROXY: ${no_proxy}
  no_proxy: ${no_proxy}
  HTTP_PROXY: ${http_proxy}
  http_proxy: ${http_proxy}
  HTTPS_PROXY: ${https_proxy}
  https_proxy: ${https_proxy}

---

kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: http-proxy
spec:
  selector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-version-operator
      - tectonic-channel-operator
  envFrom:
    - configMapRef:
        name: http-proxy-env-config
